In [1]:
import pandas as pd

In [346]:
roster = pd.read_html('http://www.cfbstats.com/2016/team/811/roster.html')

In [347]:
roster2018 = roster[0]

In [348]:
punting = pd.read_html('http://www.cfbstats.com/2016/team/811/punting/index.html')
ko = pd.read_html('http://www.cfbstats.com/2016/team/811/kickoff/index.html')
kick = pd.read_html('http://www.cfbstats.com/2016/team/811/kicking/index.html')
score = pd.read_html('http://www.cfbstats.com/2016/team/811/scoring/index.html')
to = pd.read_html('http://www.cfbstats.com/2016/team/811/total/index.html')
allpurpose = pd.read_html('http://www.cfbstats.com/2016/team/811/allpurpose/index.html')
interception = pd.read_html('http://www.cfbstats.com/2016/team/811/interception/index.html')
tackle = pd.read_html('http://www.cfbstats.com/2016/team/811/tackle/index.html')
sack = pd.read_html('http://www.cfbstats.com/2016/team/811/sack/index.html')
passing = pd.read_html('http://www.cfbstats.com/2016/team/811/passing/index.html')

In [349]:
punting = punting[0]
kickoffs = ko[0]
place_kicking = kick[0]
scoring = score[0]
total_offense = to[0]
all_purpose_running = allpurpose[0]
interceptions = interception[0]
tackles = tackle[0]
sacks = sack[0]
passing = passing[0]

In [350]:
punting.dropna(inplace=True)
kickoffs.dropna(inplace=True)
place_kicking.dropna(inplace=True)
scoring.dropna(inplace=True)
total_offense.dropna(inplace=True)
all_purpose_running.dropna(inplace=True)
interceptions.dropna(inplace=True)
tackles.dropna(inplace=True)
sacks.dropna(inplace=True)
passing.dropna(inplace=True)

In [351]:
roster2018.head()

,No,Name,Pos,Yr,Ht,Wt,Hometown,Last School
0,17,"Allen, Josh",QB,SO,6-5,222,"Firebaugh, CA","Reedley College CC, Calif."
1,57,"Appleby, Chase",NT,SR,6-0,268,"Frisco, TX",Centennial
2,76,"Baker, Darius",DT,JR,6-3,289,"Dodge City, KS",Dodge City CC
3,97,"Baker, Ja'Chai",DT,FR,6-6,283,"Council Bluffs, IA",Lewis Central
4,69,"Bettencourt, Richard",OG,SO,6-3,310,"Meridian, ID",Meridian

In [352]:
def clean_names(df_column):
    
    new_column = []

    for name in df_column:
        
        names = name.split(',')
        new_column.append(names[1].strip() + ' ' + names[0])
        
    rosternames = pd.Series(new_column)
    roster2018['Name'] = rosternames
clean_names(roster2018['Name'])

In [353]:
kickoffs = kickoffs[['Name', 'Kickoffs', 'Yards', 'Touchback']]
passing = passing[['Name', 'Att', 'Comp', 'TD', 'Int']]
passing.rename(columns={'TD': 'Passing TD', 'Int': 'Passing Int'}, inplace=True)
punting = punting[['Name', 'Punts', 'Yards']]
scoring = scoring[['Name', 'G', 'TD', 'FG', '1XP', '2XP', 'Safety', 'Points']]
total_offense = total_offense[['Name', 'Rush Yards', 'Pass Yards', 'Plays', 'Total Yards', 'Yards/Play']]
all_purpose_running = all_purpose_running[['Name', 'Recv.', 'Punt Ret.', 'Kick Ret.', 'Total Yards']]
interceptions = interceptions[['Name', 'Int.']]
tackles = tackles[['Name', 'Solo', 'Assisted']]
sacks = sacks[['Name', 'Sacks', 'Sack Yards']]

In [354]:
wy1 = roster2018.merge(kickoffs, how='outer',on='Name')
wy0 = wy1.merge(passing, how='outer',on='Name')
wy2 = wy0.merge(punting, how='outer',on='Name')
wy3 = wy2.merge(scoring, how='outer',on='Name')
wy4 = wy3.merge(total_offense, how='outer',on='Name')
wy5 = wy4.merge(all_purpose_running, how='outer',on='Name')
wy6 = wy5.merge(interceptions, how='outer',on='Name')
wy7 = wy6.merge(tackles, how='outer',on='Name')
wy8 = wy7.merge(sacks, how='outer',on='Name')

In [355]:
# washington = uw8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# oklahoma = ok8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# ohio_st = oh8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # akron = ar8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# alabama = ab8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # arizona = az8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # arizona_st = azs8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# arkansas = ak8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# auburn = au8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# baylor = by8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# boise_st = bo8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# boston = bs8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # # bowling_green = bg8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# byu = byu8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# cal = ca8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# ucf = cf8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # central_michigan = cm8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# clemson = cl8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# colorado = co8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # colorado_st = cs8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # # duke = du8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # # east_michigan = em8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# florida = fl8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# florida_atlantic = fa8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# florida_st = fs8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# georgia = ga8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # # hawaii = hi8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# houston = ho8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# indiana = in8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# iowa = iw8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # # iowa_st = io8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # kansas = ka8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# kansas_st = ks8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # # kentucky = ku8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# lousiana_tech = lt8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# louisville = lv8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# lsu = ls8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # # maryland = ma8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # # massachusetts = ms8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# memphis = me8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
miami = mf8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
michigan = mi8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
michigan_st = mt8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
mississippi = mp8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
mississippi_st = mz8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
missouri = mx8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
nebraska = ne8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# nevada = nv8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
north_carolina = ns8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
north_carolina_st = nc8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
north_illinois = ni8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
notre_dame = nd8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
oklahoma_st = os8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# # old_dominion = od8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# oregon = or8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
penn_st = ps8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
pittsburgh = pi8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# rutgers = ru8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
sd_st = ss8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# sj_st = sj8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# southern_miss = sm8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# south_carolina = sc8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# smu = su8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
south_florida = sf8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
stanford = st8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
tcu = tc8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
tennessee = tn8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
temple = te8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
texas = tx8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
texas_am = ts8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
texas_tech = tt8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
toledo = to8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
ucla = uc8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
usc = us8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
utah = ut8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
vanderbilt = va8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# virginia = vi8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
virginia_tech = vi8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
# wake_forest = wf8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
washington_st = wa8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
west_virginia = wv8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
west_michigan = wm8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
western_kentucky = wk8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
wisconsin = wi8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]
wyoming = wy8[['Name', 'Pos', 'Yr', 'Ht', 'Wt', 'Kickoffs', 'Punts', 'TD', 'FG', '1XP', '2XP', 'Points', 'Rush Yards', 'Pass Yards', 'Recv.', 'Int.', 'Solo', 'Sacks', 'Att', 'Comp', 'Passing TD', 'Passing Int']]

In [356]:
# cfb1_2016 = pd.concat([washington, oklahoma, ohio_st, alabama, arkansas,
#                        auburn, boise_st, boston, byu, ucf, cal, clemson])
# cfb2_2018 = pd.concat([colorado, florida, florida_atlantic,
#                       florida_st, georgia, houston, iowa, indiana, kansas_st,
#                        lousiana_tech, louisville, lsu, memphis])

cfb3_2018 = pd.concat([miami, michigan, michigan_st, mississippi, mississippi_st,
                       missouri, nebraska, north_carolina, north_carolina_st, notre_dame, oklahoma_st, 
                       penn_st, pittsburgh, sd_st,
                       south_florida, stanford, 
                      tcu, temple, tennessee, texas, texas_am, texas_tech, toledo, ucla, usc, utah, vanderbilt, virginia_tech, 
                      washington_st, west_virginia, west_michigan, western_kentucky, wisconsin, wyoming])

In [313]:
cfb_2017_1 = pd.concat([cfb1_2018, cfb2_2018])

In [140]:
cfb2_2018.to_pickle('cfb1_2016_2.pickle')

In [360]:
cfb_2016 = pd.concat([cfb_2016_2, cfb_2016_1, cfb3_2018])

In [374]:
cfb_2016.to_pickle('cfb_2016.pickle')

In [357]:
cfb_2016_1 = pd.read_pickle('cfb1_2016_1.pickle')

In [358]:
cfb_2016_2 = pd.read_pickle('cfb1_2016_2.pickle')

In [331]:
cfb_2018 = pd.read_pickle('cfb_2018.pickle')

In [361]:
cfb_2016

,Name,Pos,Yr,Ht,Wt,Kickoffs,Punts,TD,FG,1XP,...,Rush Yards,Pass Yards,Recv.,Int.,Solo,Sacks,Att,Comp,Passing TD,Passing Int
0,Michael Adkins II,TB,JR,5-10,205,NaN,NaN,1.0,0.0,0.0,...,30.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jaleel Awini,WR,SR,6-2,215,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
2,Chidobe Awuzie,DB,SR,6-0,205,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1.0,53.0,4.0,NaN,NaN,NaN,NaN
3,David Bagby,WR,SR,6-0,180,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,J.T. Bale,SN,FR,6-2,205,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,Nick Wilson,WR,FR,5-11,168,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,Shiloh Windsor,DE,FR,6-3,224,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
107,Andrew Wingard,FS,SO,6-0,207,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,2.0,75.0,2.0,NaN,NaN,NaN,NaN
108,Ben Wisdorf,LB,FR,6-1,213,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Ethan Wood,K,SR,6-3,176,1.0,70.0,NaN,NaN,NaN,...,-20.0,0.0,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [362]:
cfb_2016.reset_index(drop=True, inplace=True)

In [363]:
cfb_2016.fillna(value=0, inplace=True)

In [364]:
table = pd.read_html('https://www.pro-football-reference.com/years/2017/draft.htm')

In [365]:
df = table[0]

In [366]:
df['Unnamed: 3_level_0']['Player']

0          Myles Garrett
1      Mitchell Trubisky
2         Solomon Thomas
3      Leonard Fournette
4            Corey Davis
             ...
254         Chris Carson
255         Pat O'Connor
256        Mason Schreck
257        Matthew Dayes
258           Chad Kelly
Name: Player, Length: 259, dtype: object

In [367]:
draft_list = []
for name in df['Unnamed: 3_level_0']['Player']:
    draft_list.append(name)
draft_list

['Myles Garrett',
 'Mitchell Trubisky',
 'Solomon Thomas',
 'Leonard Fournette',
 'Corey Davis',
 'Jamal Adams',
 'Mike Williams',
 'Christian McCaffrey',
 'John Ross',
 'Patrick Mahomes',
 'Marshon Lattimore',
 'Deshaun Watson',
 'Haason Reddick',
 'Derek Barnett',
 'Malik Hooker',
 'Marlon Humphrey',
 'Jonathan Allen',
 "Adoree' Jackson",
 'O.J. Howard',
 'Garett Bolles',
 'Jarrad Davis',
 'Charles Harris',
 'Evan Engram',
 'Gareon Conley',
 'Jabrill Peppers',
 'Takkarist McKinley',
 'TreDavious White',
 'Taco Charlton',
 'David Njoku',
 'T.J. Watt',
 'Reuben Foster',
 'Ryan Ramczyk',
 'Player',
 'Kevin King',
 'Cam Robinson',
 'Malik McDowell',
 'Budda Baker',
 'Zay Jones',
 'Forrest Lamp',
 'Marcus Maye',
 'Curtis Samuel',
 'Dalvin Cook',
 'Marcus Williams',
 'Sidney Jones',
 'Gerald Everett',
 'Adam Shaheen',
 'Quincy Wilson',
 'Tyus Bowser',
 'Joe Mixon',
 'Ryan Anderson',
 'Justin Evans',
 'DeMarcus Walker',
 'DeShone Kizer',
 'Teez Tabor',
 'Raekwon McMillan',
 'Dalvin Tomlinson',
 'Obi Melifonwu',
 'Zach Cunningham',
 'Ethan Pocic',
 'Tanoh Kpassagnon',
 'Chidobe Awuzie',
 'Josh Jones',
 'JuJu Smith-Schuster',
 'Dion Dawkins',
 'Taylor Moton',
 'Player',
 'Larry Ogunjobi',
 'Ahkello Witherspoon',
 'Alvin Kamara',
 'Dawuane Smoot',
 'Cooper Kupp',
 'Pat Elflein',
 'Dan Feeney',
 'Taywan Taylor',
 'Jordan Willis',
 'Chris Wormley',
 'Duke Riley',
 'Alex Anzalone',
 'Daeshon Hall',
 'Tim Williams',
 'ArDarius Stewart',
 'Tarell Basham',
 'Fabian Moreau',
 'Carlos Henderson',
 'Derek Rivers',
 'Chris Godwin',
 'Antonio Garcia',
 'Kareem Hunt',
 'Davis Webb',
 'Eddie Vanderdoes',
 "D'Onta Foreman",
 'Shaquill Griffin',
 'John Johnson',
 'Jourdan Lewis',
 'Montravius Adams',
 'Cameron Sutton',
 'Delano Hill',
 'Kenny Golladay',
 'Cordrea Tankersley',
 'Chad Williams',
 'Rasul Douglas',
 'Jonnu Smith',
 'Brendan Langley',
 'Nazair Jones',
 'Trey Hendrickson',
 'C.J. Beathard',
 'James Conner',
 'Amara Darboh',
 'Kendell Beckwith',
 'Player',
 'Vince Biegel',
 'Jaleel Johnson',
 'Dede Westbrook',
 'Tedric Thompson',
 'Eddie Jackson',
 'Rayshawn Jenkins',
 'Samaje Perine',
 'Dorian Johnson',
 'Carl Lawson',
 'Josh Reynolds',
 'Mack Hollins',
 'Tarik Cohen',
 'Ben Gedeon',
 'Joe Williams',
 'Nico Siragusa',
 'Montae Nicholson',
 'Jalen Reeves-Maybin',
 'Samson Ebukam',
 'Howard Wilson',
 'Michael Roberts',
 'Josh Malone',
 'David Sharpe',
 "Julie'n Davenport",
 'Deatrich Wise',
 'Donnel Pumphrey',
 'Ryan Switzer',
 'Jamaal Williams',
 'Joshua Dobbs',
 'Sean Harlow',
 'Zach Banner',
 'Ryan Glasgow',
 'Jehu Chesson',
 'Wayne Gallman',
 'Chad Hansen',
 'Carlos Watkins',
 'Marlon Mack',
 'Grover Stewart',
 'Player',
 'Jake Butt',
 'George Kittle',
 'Jordan Morgan',
 'Blair Brown',
 'Damontae Kazee',
 'Jordan Leggett',
 'Desmond King',
 'Corn Elder',
 'Jake Elliott',
 'Jeremy Sprinkle',
 'Jayon Brown',
 'Brian Hill',
 'Will Holden',
 'Nate Hairston',
 'Jermaine Eluemunor',
 'Roderick Johnson',
 'Anthony Walker',
 'Jeremy McNichols',
 'Matt Milano',
 'Isaac Asiata',
 'Jamal Agnew',
 'Shelton Gibson',
 'Avery Moss',
 'Marquel Lee',
 'Treston Decoud',
 'Rodney Adams',
 'Nathan Peterman',
 'Isaiah McKenzie',
 'Brian Allen',
 'Eric Saubert',
 'DeAngelo Yancey',
 'JJ Dielman',
 'Trent Taylor',
 'Davon Godchaux',
 'T.J. Logan',
 'Danny Isidora',
 'Dylan Donahue',
 'Aaron Jones',
 'Ukeme Eligwe',
 'Nathan Gerry',
 'Player',
 'Caleb Brantley',
 'Chuck Clark',
 'Michael Tyson',
 'Elijah McGuire',
 'Tanzel Smart',
 'Sam Tevi',
 'Xavier Woods',
 'Alex Armah',
 'Jordan Evans',
 'Vincent Taylor',
 'Tanner Vallejo',
 'Al-Quadin Muhammad',
 'Jeremy Clark',
 'D.J. Jones',
 'Chase Roullier',
 'Adam Bisnowaty',
 'Bucky Hodges',
 'Pita Taumoepenu',
 "De'Angelo Henderson",
 'Derrick Jones',
 'Jeremiah Ledbetter',
 'Sam Rogers',
 'Brandon Wilson',
 'Rudy Ford',
 'Robert Davis',
 'Justin Senior',
 'Conor McDermott',
 'Kofi Amichia',
 'Colin Holba',
 'Elijah Qualls',
 'Brad Kaaya',
 'Marquez White',
 'Corey Levin',
 'Leon McQuay',
 'Player',
 'Stacy Coley',
 'Ifeadi Odenigbo',
 'Shalom Luani',
 'Jalen Myrick',
 "Stevie Tu'ikolovatu",
 'Zane Gonzalez',
 'Isaac Rochell',
 'David Moore',
 'Josh Carraway',
 'Joey Ivie',
 'Adrian Colbert',
 'Josh Harvey-Clemons',
 'Jylan Ware',
 'Elijah Lee',
 'Harrison Butker',
 'Ejuan Price',
 'Joshua Holsey',
 'Brad Seaton',
 'Isaiah Ford',
 'Devante Mays',
 'Noah Brown',
 'Marquez Williams',
 'Khalfani Muhammad',
 'Elijah Hood',
 'Kyle Fuller',
 'Treyvon Hester',
 'Jack Tocho',
 'Jordan Carrell',
 'Malachi Dupre',
 'Keion Adams',
 'Chris Carson',
 "Pat O'Connor",
 'Mason Schreck',
 'Matthew Dayes',
 'Chad Kelly']

In [369]:
drafted = []
for name in cfb_2016['Name']:
    if name in draft_list:
        drafted.append('Yes')
    else:
        drafted.append('No')
drafted_series = pd.Series(drafted)   
cfb_2016['Drafted'] = drafted_series

In [370]:
cfb_2016['Drafted'].value_counts()

No     6657
Yes     198
Name: Drafted, dtype: int64

In [371]:
cfb_2016

,Name,Pos,Yr,Ht,Wt,Kickoffs,Punts,TD,FG,1XP,...,Pass Yards,Recv.,Int.,Solo,Sacks,Att,Comp,Passing TD,Passing Int,Drafted
0,Michael Adkins II,TB,JR,5-10,205,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
1,Jaleel Awini,WR,SR,6-2,215,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,No
2,Chidobe Awuzie,DB,SR,6-0,205,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,53.0,4.0,0.0,0.0,0.0,0.0,Yes
3,David Bagby,WR,SR,6-0,180,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
4,J.T. Bale,SN,FR,6-2,205,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6850,Nick Wilson,WR,FR,5-11,168,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
6851,Shiloh Windsor,DE,FR,6-3,224,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,No
6852,Andrew Wingard,FS,SO,6-0,207,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,75.0,2.0,0.0,0.0,0.0,0.0,No
6853,Ben Wisdorf,LB,FR,6-1,213,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
6854,Ethan Wood,K,SR,6-3,176,1.0,70.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,No

In [372]:
drafted_df = cfb_2016.loc[cfb_2016['Drafted']=='Yes']

In [373]:
drafted_df

,Name,Pos,Yr,Ht,Wt,Kickoffs,Punts,TD,FG,1XP,...,Pass Yards,Recv.,Int.,Solo,Sacks,Att,Comp,Passing TD,Passing Int,Drafted
2,Chidobe Awuzie,DB,SR,6-0,205,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,53.0,4.0,0.0,0.0,0.0,0.0,Yes
14,Jordan Carrell,DE,SR,6-3,300,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,24.0,5.0,0.0,0.0,0.0,0.0,Yes
102,Tedric Thompson,DB,SR,6-1,205,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,42.0,0.0,0.0,0.0,0.0,0.0,Yes
114,Ahkello Witherspoon,DB,SR,6-3,195,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,19.0,0.0,0.0,0.0,0.0,0.0,Yes
116,Alex Anzalone,LB,JR,6-3,241,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,22.0,3.0,0.0,0.0,0.0,0.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6637,Vince Biegel,OLB,SR,6-4,245,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,29.0,4.0,0.0,0.0,0.0,0.0,Yes
6716,Ryan Ramczyk,OL,JR,6-6,314,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes
6741,T.J. Watt,OLB,JR,6-5,243,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,38.0,11.5,0.0,0.0,0.0,0.0,Yes
6784,Brian Hill,RB,JR,6-1,219,0.0,0.0,22.0,0.0,0.0,...,0.0,67.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes
6825,Chase Roullier,OG,SR,6-4,313,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes

In [221]:
passing

                Name  Att  Comp  Passing TD  Passing Int
0        D'Eriq King  345   219          36            6
1       Clayton Tune  117    59           8            2
2  Marquez Stevenson    1     1           0            0
3       Bryson Smith    5     2           1            1
4    Quinten Dormady    5     2           0            0
5         Ike Ogbogu    1     1           0            0